(function(){
  const DEFAULTS = {
    ingredients: {
      burger_bun: { name: 'Burger Bun', category: 'bread', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 80, moq_storage: 60, moq_foodtruck: 20 },
      beef_patty: { name: 'Beef Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 180, current_stock_foodtruck: 60, moq_storage: 50, moq_foodtruck: 16 },
      chicken_patty: { name: 'Chicken Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 120, current_stock_foodtruck: 40, moq_storage: 30, moq_foodtruck: 10 },
      chicken_shawarma_patty: { name: 'Chicken Shawarma Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 120, current_stock_foodtruck: 40, moq_storage: 30, moq_foodtruck: 10 },
      cheese_slice: { name: 'Cheese Slice', category: 'dairy', unit: 'slice', track_stock: true, stock_location: 'both', current_stock_storage: 250, current_stock_foodtruck: 120, moq_storage: 80, moq_foodtruck: 24 },
      lettuce_pack: { name: 'Lettuce Pack', category: 'veg', unit: 'pack', purchase_unit: 'pack', recipe_unit: 'pack', yield_note: '1 supplier pack ≈ 30 burgers, 6 standard salads or 4 large salads', purchase_options: [{ label:'Supplier pack', factor:1 }], track_stock: true, stock_location: 'both', current_stock_storage: 12, current_stock_foodtruck: 4, moq_storage: 4, moq_foodtruck: 1 },
      onion: { name: 'Onion', category: 'veg', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 80, current_stock_foodtruck: 20, moq_storage: 20, moq_foodtruck: 8 },
      onion_diced: { name: 'Onion Diced', category: 'veg', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 3000, current_stock_foodtruck: 1000, moq_storage: 600, moq_foodtruck: 250 },
      tomato: { name: 'Tomato', category: 'veg', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 120, current_stock_foodtruck: 30, moq_storage: 24, moq_foodtruck: 10 },
      pickle: { name: 'Pickle', category: 'veg', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 150, current_stock_foodtruck: 50, moq_storage: 30, moq_foodtruck: 12 },
      ketchup: { name: 'Ketchup', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 5000, current_stock_foodtruck: 2000, moq_storage: 1000, moq_foodtruck: 500 },
      mayonnaise: { name: 'Mayonnaise', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 5000, current_stock_foodtruck: 2000, moq_storage: 1000, moq_foodtruck: 500 },
      mustard: { name: 'Mustard', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 2500, current_stock_foodtruck: 1000, moq_storage: 500, moq_foodtruck: 250 },
      chicken_burger_sauce: { name: 'Chicken Burger Sauce', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 2000, current_stock_foodtruck: 800, moq_storage: 500, moq_foodtruck: 200 },
      chicken_wings_sauce: { name: 'Chicken Wings Sauce', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 2000, current_stock_foodtruck: 800, moq_storage: 500, moq_foodtruck: 200 },
      fries: { name: 'Fries Raw', category: 'fries', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 30000, current_stock_foodtruck: 10000, moq_storage: 8000, moq_foodtruck: 3000 },
      sauce_cup: { name: 'Sauce Cup', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 500, current_stock_foodtruck: 200, moq_storage: 120, moq_foodtruck: 40 },
      standard_fries_cup: { name: 'Standard Fries Cup', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 400, current_stock_foodtruck: 150, moq_storage: 100, moq_foodtruck: 40 },
      large_fries_cup: { name: 'Large Fries Cup', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 300, current_stock_foodtruck: 120, moq_storage: 80, moq_foodtruck: 30 },
      small_paper_box: { name: 'Small Paper Box', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 80, moq_storage: 60, moq_foodtruck: 20 },
      large_paper_box: { name: 'Large Paper Box', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 80, moq_storage: 60, moq_foodtruck: 20 },
      aluminium_foil: { name: 'Aluminium Foil', category: 'packaging', unit: 'cm', track_stock: true, stock_location: 'both', current_stock_storage: 20000, current_stock_foodtruck: 8000, moq_storage: 4000, moq_foodtruck: 1500 },
      small_bag: { name: 'Small Bag', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 500, current_stock_foodtruck: 180, moq_storage: 120, moq_foodtruck: 50 },
      large_bag: { name: 'Large Bag', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 300, current_stock_foodtruck: 120, moq_storage: 80, moq_foodtruck: 30 },
      napkin: { name: 'Napkin', category: 'packaging', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 3000, current_stock_foodtruck: 1200, moq_storage: 600, moq_foodtruck: 250 },
      chicken_wing: { name: 'Chicken Wing', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 500, current_stock_foodtruck: 300, moq_storage: 150, moq_foodtruck: 80 },
      cucumber: { name: 'Cucumber', category: 'veg', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 60, current_stock_foodtruck: 20, moq_storage: 16, moq_foodtruck: 6 },
      carrot: { name: 'Carrot', category: 'veg', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 80, current_stock_foodtruck: 24, moq_storage: 20, moq_foodtruck: 8 },
      egg: { name: 'Egg', category: 'protein', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 140, current_stock_foodtruck: 60, moq_storage: 36, moq_foodtruck: 14 },
      pasta_g: { name: 'Pasta / Macaroni', category: 'salad', unit: 'g', purchase_unit: '500g pack', recipe_unit: 'g', yield_note: '1 pasta pack = 500g; salad portions consume grams', purchase_options: [{ label:'500g pack', factor:500 }, { label:'1kg pack', factor:1000 }], track_stock: true, stock_location: 'both', current_stock_storage: 60000, current_stock_foodtruck: 20000, moq_storage: 15000, moq_foodtruck: 5000 },
      softdrink_cola: { name: 'Softdrink Cola', category: 'drinks', unit: 'can', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 100, moq_storage: 50, moq_foodtruck: 20 },
      softdrink_sprite: { name: 'Softdrink Sprite', category: 'drinks', unit: 'can', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 100, moq_storage: 50, moq_foodtruck: 20 },
      softdrink_fanta_orange: { name: 'Softdrink Fanta Orange', category: 'drinks', unit: 'can', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 100, moq_storage: 50, moq_foodtruck: 20 },
      iced_tea_lime: { name: 'Iced Tea Lime', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      iced_tea_ginger: { name: 'Iced Tea Ginger', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      iced_tea_strawberry: { name: 'Iced Tea Strawberry', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      iced_tea_pineapple: { name: 'Iced Tea Pineapple', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      iced_tea_mint: { name: 'Iced Tea Mint', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      iced_tea_apple: { name: 'Iced Tea Apple', category: 'drinks', unit: 'cup', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 40, moq_storage: 0, moq_foodtruck: 10 },
      gas_bottle: { name: 'Gas Bottle', category: 'operating_supply', unit: 'bottle', purchase_unit: 'bottle', recipe_unit: 'bottle', operating_supply: true, yield_note: 'Operating supply tracked by bottle and last purchase amount', track_stock: true, stock_location: 'both', current_stock_storage: 1, current_stock_foodtruck: 1, moq_storage: 1, moq_foodtruck: 1 }
    },
    recipes: {
      hamburger: { burger_bun:1, beef_patty:1, lettuce_pack:0.0333, onion:0.5, tomato:0.5, pickle:0.25, ketchup:20, mayonnaise:20, mustard:10, aluminium_foil:30, small_bag:1, napkin:2 },
      cheeseburger: { burger_bun:1, beef_patty:1, cheese_slice:1, lettuce_pack:0.0333, onion:0.5, tomato:0.5, pickle:0.25, ketchup:20, mayonnaise:20, mustard:10, aluminium_foil:30, small_bag:1, napkin:2 },
      double_burger: { burger_bun:1, beef_patty:2, lettuce_pack:0.0333, onion:0.5, tomato:0.5, pickle:0.25, ketchup:20, mayonnaise:20, mustard:10, aluminium_foil:30, small_bag:1, napkin:2 },
      double_cheeseburger: { burger_bun:1, beef_patty:2, cheese_slice:2, lettuce_pack:0.0333, onion:0.5, tomato:0.5, pickle:0.25, ketchup:20, mayonnaise:20, mustard:10, aluminium_foil:30, small_bag:1, napkin:2 },
      chicken_burger: { burger_bun:1, chicken_patty:1, lettuce_pack:0.0333, onion:0.5, tomato:0.5, chicken_burger_sauce:50, aluminium_foil:30, small_bag:1, napkin:2 },
      chicken_shawarma_burger: { burger_bun:1, chicken_shawarma_patty:1, lettuce_pack:0.0333, onion:0.5, tomato:0.5, chicken_burger_sauce:50, aluminium_foil:30, small_bag:1, napkin:2 },
      fries_standard: { fries:130, sauce_cup:1, standard_fries_cup:1, aluminium_foil:10, small_bag:1, napkin:2 },
      fries_large: { fries:170, sauce_cup:2, large_fries_cup:1, aluminium_foil:10, small_bag:1, napkin:2 },
      fries_family: { fries:600, sauce_cup:4, large_bag:1, napkin:2 },
      wings_6: { chicken_wing:6, chicken_wings_sauce:20, large_fries_cup:1, aluminium_foil:10, small_bag:1, napkin:2 },
      wings_12: { chicken_wing:12, chicken_wings_sauce:40, small_paper_box:1, large_bag:1, napkin:2 },
      wings_24: { chicken_wing:24, chicken_wings_sauce:80, large_paper_box:1, large_bag:1, napkin:2 },
      salad_standard: { lettuce_pack:0.1667, tomato:1, cucumber:0.166, carrot:0.25, onion:0.5, egg:1, pasta_g:80, small_paper_box:1, large_bag:1, napkin:2 },
      salad_large: { lettuce_pack:0.25, tomato:1.5, cucumber:0.25, carrot:0.25, onion:0.5, egg:2, pasta_g:120, large_paper_box:1, large_bag:1, napkin:2 },
      d_cola: { softdrink_cola:1 },
      d_sprite: { softdrink_sprite:1 },
      d_fanta_orange: { softdrink_fanta_orange:1 },
      d_iced_tea_lime: { iced_tea_lime:1 },
      d_iced_tea_ginger: { iced_tea_ginger:1 },
      d_iced_tea_strawberry: { iced_tea_strawberry:1 },
      d_iced_tea_pineapple: { iced_tea_pineapple:1 },
      d_iced_tea_mint: { iced_tea_mint:1 },
      d_iced_tea_apple: { iced_tea_apple:1 },
      x_beef_patty: { beef_patty:1 },
      x_chicken_patty: { chicken_patty:1 },
      x_chicken_shawarma_patty: { chicken_shawarma_patty:1 },
      x_cheese: { cheese_slice:1 },
      x_fried_egg: { egg:1 },
      x_omelette: { egg:2 },
      i_sauce_ketchup: { ketchup:20 },
      i_sauce_mayonnaise: { mayonnaise:20 },
      i_sauce_chipotle: { mayonnaise:15, chicken_burger_sauce:5 },
      i_sauce_dutch_special: { mayonnaise:10, ketchup:10, onion_diced:5 },
      i_sauce_chicken_wings: { chicken_wings_sauce:20 },
      x_sauce_ketchup: { ketchup:20, sauce_cup:1 },
      x_sauce_mayonnaise: { mayonnaise:20, sauce_cup:1 },
      x_sauce_chipotle: { mayonnaise:15, chicken_burger_sauce:5, sauce_cup:1 },
      x_sauce_dutch_special: { mayonnaise:10, ketchup:10, onion_diced:5, sauce_cup:1 },
      x_sauce_chicken_wings: { chicken_wings_sauce:20, sauce_cup:1 }
    }
  };
  window.BK_STOCK_DATA = { DEFAULTS };
})();
