(function(){
  const DEFAULTS = {
    ingredients: {
      bun: { name: 'Burger Bun', category: 'bread', unit: 'pcs', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 80, moq_storage: 20, moq_foodtruck: 16 },
      beef_patty: { name: 'Beef Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 120, current_stock_foodtruck: 60, moq_storage: 40, moq_foodtruck: 12 },
      cheese_slice: { name: 'Cheese Slice', category: 'dairy', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 120, moq_storage: 80, moq_foodtruck: 24 },
      chicken_wing: { name: 'Chicken Wing', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 400, current_stock_foodtruck: 300, moq_storage: 120, moq_foodtruck: 60 },
      fries_portion: { name: 'Fries Portion', category: 'sides', unit: 'portion', track_stock: true, stock_location: 'both', current_stock_storage: 150, current_stock_foodtruck: 120, moq_storage: 50, moq_foodtruck: 20 },
      coconut_fresh: { name: 'Coconut Fresh', category: 'drinks', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 40, current_stock_foodtruck: 25, moq_storage: 12, moq_foodtruck: 6 },
      soda_can: { name: 'Soft Drink', category: 'drinks', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 240, current_stock_foodtruck: 120, moq_storage: 72, moq_foodtruck: 24 },
      ice_tea: { name: 'Ice Tea', category: 'drinks', unit: 'cups', track_stock: true, stock_location: 'foodtruck', current_stock_storage: 0, current_stock_foodtruck: 30, moq_storage: 0, moq_foodtruck: 8 },
      coconut_water_bottle: { name: 'Coconut Water Bottle', category: 'drinks', unit: 'btl', track_stock: true, stock_location: 'both', current_stock_storage: 48, current_stock_foodtruck: 30, moq_storage: 16, moq_foodtruck: 8 },
      beer: { name: 'Beer', category: 'drinks', unit: 'btl', track_stock: true, stock_location: 'both', current_stock_storage: 96, current_stock_foodtruck: 48, moq_storage: 24, moq_foodtruck: 12 },
      egg: { name: 'Egg', category: 'protein', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 96, current_stock_foodtruck: 48, moq_storage: 24, moq_foodtruck: 12 },
      chicken_patty: { name: 'Chicken Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 80, current_stock_foodtruck: 40, moq_storage: 24, moq_foodtruck: 12 },
      chicken_shawarma_patty: { name: 'Chicken Shawarma Patty', category: 'meat', unit: 'pcs', track_stock: true, stock_location: 'both', current_stock_storage: 80, current_stock_foodtruck: 40, moq_storage: 24, moq_foodtruck: 12 },
      bacon_slice: { name: 'Bacon Slice', category: 'protein', unit: 'slice', track_stock: true, stock_location: 'both', current_stock_storage: 200, current_stock_foodtruck: 120, moq_storage: 60, moq_foodtruck: 24 },
ketchup: { name: 'Ketchup', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 5000, current_stock_foodtruck: 2000, moq_storage: 1000, moq_foodtruck: 500 },
      mayonnaise: { name: 'Mayonnaise', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 5000, current_stock_foodtruck: 2000, moq_storage: 1000, moq_foodtruck: 500 },
      chicken_burger_sauce: { name: 'Chicken Burger Sauce', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 2000, current_stock_foodtruck: 800, moq_storage: 500, moq_foodtruck: 200 },
      chicken_wings_sauce: { name: 'Chicken Wings Sauce', category: 'sauce', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 2000, current_stock_foodtruck: 800, moq_storage: 500, moq_foodtruck: 200 },
      onion_diced: { name: 'Onion Diced', category: 'veg', unit: 'g', track_stock: true, stock_location: 'both', current_stock_storage: 3000, current_stock_foodtruck: 1000, moq_storage: 600, moq_foodtruck: 250 },
    },
    recipes: {
      hamburger: { bun: 1, beef_patty: 1 },
      cheeseburger: { bun: 1, beef_patty: 1, cheese_slice: 1 },
      double_burger: { bun: 1, beef_patty: 2 },
      double_cheeseburger: { bun: 1, beef_patty: 2, cheese_slice: 1 },
      chicken_burger: { bun: 1, chicken_patty: 1 },
      chicken_shawarma_burger: { bun: 1, chicken_shawarma_patty: 1 },
      wings_6: { chicken_wing: 6 },
      wings_12: { chicken_wing: 12 },
      wings_24: { chicken_wing: 24 },
      fries_standard: { fries_portion: 1 },
      fries_large: { fries_portion: 2 },
      fries_family: { fries_portion: 4 },
      x_beef_patty: { beef_patty: 1 },
      x_chicken_patty: { chicken_patty: 1 },
      x_chicken_shawarma_patty: { chicken_shawarma_patty: 1 },
      x_cheese: { cheese_slice: 1 },
      x_bacon: { bacon_slice: 1 },
      x_fried_egg: { egg: 1 },
      x_omelette: { egg: 2 },
      x_sauce_ketchup: { ketchup: 20 },
      x_sauce_mayonnaise: { mayonnaise: 20 },
      x_sauce_chipotle: { mayonnaise: 15, chicken_burger_sauce: 5 },
      x_sauce_dutch_special: { mayonnaise: 10, ketchup: 10, onion_diced: 5 },
      x_sauce_chicken_wings: { chicken_wings_sauce: 20 },
      d_coconut_fresh: { coconut_fresh: 1 },
      d_coconut_water_bottle: { coconut_water_bottle: 1 },
      d_cola: { soda_can: 1 },
      d_sprite: { soda_can: 1 },
      d_fanta_orange: { soda_can: 1 },
      d_fanta_coktail: { soda_can: 1 },
      d_biggoo_grape: { soda_can: 1 },
      d_iced_tea_lime: { ice_tea: 1 },
      d_iced_tea_ginger: { ice_tea: 1 },
      d_iced_tea_strawberry: { ice_tea: 1 },
      d_iced_tea_pineapple: { ice_tea: 1 },
      d_iced_tea_mint: { ice_tea: 1 },
      d_iced_tea_apple: { ice_tea: 1 },
      d_iced_tea_green_mint: { ice_tea: 1 },
      d_iced_tea_vannile: { ice_tea: 1 },
      d_club_beer_std: { beer: 1 },
      d_club_beer_large: { beer: 1 },
      d_guinness: { beer: 1 }
    }
  };
  window.BK_STOCK_DATA = { DEFAULTS };
})();
