const assert = require('assert');
const fs = require('fs');

const addons = fs.readFileSync('addons.js', 'utf8');
const sides = fs.readFileSync('sides.js', 'utf8');
const drinks = fs.readFileSync('drinks.js', 'utf8');
const modifiers = fs.readFileSync('modifiers.js', 'utf8');
const catalog = fs.readFileSync('catalog.js', 'utf8');
const products = fs.readFileSync('products.js', 'utf8');
const ui = fs.readFileSync('ui.js', 'utf8');
const css = fs.readFileSync('style.css', 'utf8');
const data = fs.readFileSync('data.js', 'utf8');
const orderHtml = fs.readFileSync('order.html', 'utf8');
const adminHtml = fs.readFileSync('admin.html', 'utf8');

assert.match(addons, /window\.BK_ADDONS/);
assert.match(addons, /ADDON_CATEGORY = 'extra'/);
assert.match(addons, /x_caramelized_onions/);
assert.match(addons, /x_minced_meat/);
assert.match(addons, /x_salad_chicken_wings/);
assert.match(sides, /window\.BK_SIDES/);
assert.match(sides, /DEFAULT_SIDES = \['fries_standard','fries_large','fries_family'\]/);
assert.match(drinks, /window\.BK_DRINKS/);
assert.match(drinks, /DEFAULT_DRINKS = \['d_cola'/);
assert.match(modifiers, /window\.BK_MODIFIERS/);
assert.match(modifiers, /title:'Product add-ons'/);
assert.match(modifiers, /title:'Suggested sides'/);
assert.match(modifiers, /title:'Suggested drinks'/);
assert.match(modifiers, /function preferredDrinkOptions/);
assert.match(modifiers, /function bucketForProduct/);
assert.match(catalog, /function modifierEditor/);
assert.match(catalog, /data-choice-kind="\$\{kind\}"/);
assert.match(catalog, /Suggested sides/);
assert.match(catalog, /Suggested drinks/);
assert.match(catalog, /sides:Array\.isArray\(product\.sides\)/);
assert.match(catalog, /drinks:Array\.isArray\(product\.drinks\)/);
assert.match(products, /const sourceAddons = Array\.isArray\(r && r\.addons\)/);
assert.match(products, /const sourceSides = Array\.isArray\(r && r\.sides\)/);
assert.match(products, /const sourceDrinks = Array\.isArray\(r && r\.drinks\)/);
assert.match(ui, /BK_MODIFIERS\.sectionDefinitions/);
assert.match(ui, /BK_MODIFIERS\.selectedRows/);
assert.match(ui, /BK_MODIFIERS\.bucketForProduct/);
assert.match(css, /\.catalog-addon-editor/);
assert.match(data, /BK_ADDONS\.defaultBurgerAddons\(\)/);
assert.match(data, /BK_SIDES\.defaultBurgerSides\(\)/);
assert.match(data, /BK_DRINKS\.defaultBurgerDrinks\(\)/);
assert.match(orderHtml, /addons\.js\?v=1[\s\S]*sides\.js\?v=1[\s\S]*drinks\.js\?v=1[\s\S]*modifiers\.js\?v=1[\s\S]*data\.js/);
assert.match(adminHtml, /addons\.js\?v=1[\s\S]*sides\.js\?v=1[\s\S]*drinks\.js\?v=1[\s\S]*modifiers\.js\?v=1[\s\S]*data\.js/);

console.log('Separated modifier module checks passed.');
